version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: '${BACKEND_HOST}'
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - web-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        FRONTEND_URL: '${FRONTEND_HOST}'
        DB_FILE: '/sqlite/pocket.sqlite'
    volumes:
      - ./sqlite:/sqlite
      - /backend/node_modules
    ports:
      - "${BACKEND_PORT}:80"
    networks:
      - web-network

networks:
  web-network:
    external: true
