services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: '${BACKEND_HOST}'
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - web-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        FRONTEND_URL: '${FRONTEND_HOST}'
    environment:
      DB_HOST: mysql
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - /backend/node_modules
    ports:
      - "${BACKEND_PORT}:80"
    depends_on:
      - mysql
    networks:
      - internal
      - web-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_DATABASE:
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - internal
    restart: unless-stopped

volumes:
  mysql-data:

networks:
  internal:
  web-network:
    external: true
