apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: registry.kb/pocket/backend:1.0.1
        env:
          - name: FRONTEND_URL
            value: "https://pocket.kb"
          - name: DB_HOST
            value: mysql-db.default
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: pocket-db-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pocket-db-secret
                key: password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: pocket-db-secret
                key: database
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 50m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: pocket
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: pocket
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - pocket.kb
      secretName: pocket-tls
  rules:
    - host: pocket.kb
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-svc
                port:
                  number: 80