BEGIN TRANSACTION;
CREATE TABLE passwords (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  service VARCHAAR(50) NOT NULL,
  username VARCHAAR(50) NOT NULL,
  password VARCHAAR(255) NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMP DEFAULT (DATETIME('now', 'localtime')),
  updated_at TIMESTAMP DEFAULT (DATETIME('now', 'localtime')),
  deleted_at TIMESTAMP DEFAULT NULL
);

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(20) NOT NULL UNIQUE,
  password VARCHAR(200) NOT NULL
);
COMMIT;
